POST http://localhost:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@mail.com",
    "password": "password"
}

### Get All Books
GET http://localhost:8000/api/books
Authorization: Bearer 4|5prodrpDCfCck6WCUeCAO9XH1Pg7QEpCZUkEe14ja6630081
Accept: application/json

### Add New Book
POST http://localhost:8000/api/books
Authorization: Bearer 4|5prodrpDCfCck6WCUeCAO9XH1Pg7QEpCZUkEe14ja6630081
Content-Type: application/json
Accept: application/json

{
    "judul": "Filosofi Teras",
    "penulis": "Henry Manampiring",
    "stok": 12
}